# Generated by Django 5.1.7 on 2025-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
