# Generated by Django 5.1.7 on 2025-12-17 08:45

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='images/'),
        ),
    ]
